# Generated by Django 5.0 on 2024-02-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pass1', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
